# fluentがnginxのアクセスログを読んで別ファイルに書き出す
# docker-compose up -d

nginx:
    container_name: nginx
    image: pospome/nginx-html:1.0
    ports: 
        - "80:80"
    volumes_from: 
        - dvc1
    volumes:
        - /etc/localtime:/etc/localtime:ro

fluent:
    container_name: fluent
    image: pospome/fluent-nginx-log:1.0
    ports: 
        - "24224:24224"
    volumes_from: 
        - dvc1
    volumes:
        - /etc/localtime:/etc/localtime:ro

dvc:
    container_name: dvc
    image: busybox
    volumes: 
        - /var/log/nginx/
    command: [/bin/sh]
